export const recommendedMovies = [
  {
    title: 'Bumblebee',
    originalTitle: 'Bumblebee',
    tagline: 'Todo herói tem um começo.',
    overview:
      'Refugiado num ferro-velho na Califórnia, Bumblebee é encontrado e consertado pela jovem Charlie. Quando o revive, ela percebe que este não é um fusca amarelo comum.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/c5e94e35-14c8-4023-ac2a-bb301f1647cc',
    releaseDate: new Date('2018-12-20'),
    runtime: 114,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 5704,
    voteAverage: 67.0,
    budget: BigInt(135000000),
    revenue: BigInt(467989646),
    profit: BigInt(332989646),
    genres: ['Ação', 'Aventura', 'Ficção Científica'],
  },
  {
    title: 'Capitã Marvel',
    originalTitle: 'Captain Marvel',
    tagline: 'Mais rápido, mais alto, mais forte.',
    overview:
      'Capitã Marvel acompanha a jornada de Carol Danvers, enquanto ela se torna uma das heroínas mais poderosas do universo, quando a Terra é pega no meio de uma guerra galáctica entre duas raças alienígenas.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/c78942dd-ba85-455c-b3e1-37d55ce57b53',
    releaseDate: new Date('2019-03-07'),
    runtime: 124,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 13000,
    voteAverage: 70.0,
    budget: BigInt(152000000),
    revenue: BigInt(1128000000),
    profit: BigInt(976000000),
    genres: ['Ação', 'Aventura'],
  },
  {
    title: 'Alita: Anjo de Combate',
    originalTitle: 'Alita: Battle Angel',
    tagline: 'Um anjo cai. Um guerreiro levanta.',
    overview:
      'Uma ciborgue é descoberta por um cientista. Ela não tem memória de sua vida anterior, exceto pelo seu treinamento em uma arte marcial letal. Depois de reconstruída, ela se torna uma caçadora de recompensas.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/548901b3-2367-4166-ab5b-f7b82089e8f6',
    releaseDate: new Date('2019-02-14'),
    runtime: 122,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '14 ANOS',
    voteCount: 7500,
    voteAverage: 75.0,
    budget: BigInt(170000000),
    revenue: BigInt(404852543),
    profit: BigInt(234852543),
    genres: ['Ficção científica', 'Ação'],
  },
  {
    title: 'Como Treinar o seu Dragão 3',
    originalTitle: 'How to Train Your Dragon: The Hidden World',
    tagline: 'A amizade de uma vida inteira.',
    overview:
      'Soluço e Banguela finalmente descobrirão seus verdadeiros destinos: o chefe da aldeia como governante de Berk ao lado de Astrid, e o dragão como líder de sua própria espécie.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/568edce3-8ff2-4486-af01-7775b5dc9792',
    releaseDate: new Date('2019-01-17'),
    runtime: 104,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: 'Livre',
    voteCount: 6000,
    voteAverage: 82.0,
    budget: BigInt(129000000),
    revenue: BigInt(521799505),
    profit: BigInt(392799505),
    genres: ['Infantil', 'Aventura'],
  },
  {
    title: 'Aquaman',
    originalTitle: 'Aquaman',
    tagline: 'O lar está chamando.',
    overview:
      'Arthur Curry, o herdeiro relutante do reino subaquático de Atlântida, deve dar um passo à frente para liderar seu povo e ser um herói para o mundo.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/f88e72e8-7c62-444a-9cbd-e750347cb030',
    releaseDate: new Date('2018-12-13'),
    runtime: 143,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 11000,
    voteAverage: 68.0,
    budget: BigInt(160000000),
    revenue: BigInt(1148485886),
    profit: BigInt(988485886),
    genres: ['Ação', 'Aventura'],
  },
  {
    title: 'O Menino que Queria Ser Rei',
    originalTitle: 'The Kid Who Would Be King',
    tagline: 'O destino não escolhe quem é digno.',
    overview:
      'Alex é um garoto comum que descobre a mítica espada Excalibur. Agora ele deve reunir seus amigos e inimigos em uma equipe de cavaleiros para derrotar a malvada feiticeira Morgana.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/68ff7de6-6698-4dc1-94c5-3558e377c042',
    releaseDate: new Date('2019-01-25'),
    runtime: 120,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '10 ANOS',
    voteCount: 1500,
    voteAverage: 60.0,
    budget: BigInt(59000000),
    revenue: BigInt(32140357),
    profit: BigInt(-26859643),
    genres: ['Fantasia', 'Aventura'],
  },
  {
    title: 'Megarrromântico',
    originalTitle: "Isn't It Romantic",
    tagline: 'Uma comédia sobre o amor que você não vai acreditar.',
    overview:
      'Uma arquiteta cética em relação ao amor acorda e descobre que sua vida se transformou em uma comédia romântica, e ela é a protagonista.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/2214f3d1-6e21-4927-9027-d96118da212f',
    releaseDate: new Date('2019-02-13'),
    runtime: 89,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 3000,
    voteAverage: 65.0,
    budget: BigInt(31000000),
    revenue: BigInt(48800000),
    profit: BigInt(17800000),
    genres: ['Romance', 'Comédia'],
  },
  {
    title: 'Uma Nova Chance',
    originalTitle: 'Second Act',
    tagline: 'Seu passado não define seu futuro.',
    overview:
      'Maya é uma mulher inteligente que trabalha em uma loja de departamentos local. Ao falsificar seu currículo para conseguir um emprego corporativo de alto nível, ela prova que o conhecimento das ruas é tão valioso quanto um diploma universitário.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/f6611476-37a0-4654-8725-a2c8fe74e892',
    releaseDate: new Date('2018-12-21'),
    runtime: 103,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 2000,
    voteAverage: 72.0,
    budget: BigInt(16000000),
    revenue: BigInt(72287231),
    profit: BigInt(56287231),
    genres: ['Romance', 'Comédia'],
  },
  {
    title: 'Homem-Aranha no Aranhaverso',
    originalTitle: 'Spider-Man: Into the Spider-Verse',
    tagline: 'Qualquer um pode usar a máscara.',
    overview:
      'Miles Morales é um jovem que se torna o Homem-Aranha de sua reality reality, mas ele logo descobre que não está sozinho quando outras versões do herói de diferentes dimensões aparecem para ajudá-lo a salvar o multiverso.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/09c7d4ef-7b94-47ae-9c27-a47eab38f062',
    releaseDate: new Date('2018-12-14'),
    runtime: 117,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: 'Livre',
    voteCount: 12000,
    voteAverage: 95.0,
    budget: BigInt(90000000),
    revenue: BigInt(375540831),
    profit: BigInt(285540831),
    genres: ['Ficção científica', 'Ação'],
  },
  {
    title: 'Máquinas Mortais',
    originalTitle: 'Mortal Engines',
    tagline: 'Algumas cidades foram feitas para correr.',
    overview:
      'Milhares de anos depois que o mundo foi destruído por um evento cataclísmico, a civilização se adaptou a um novo modo de vida. Cidades móveis gigantes agora vagam pela Terra, caçando impiedosamente cidades menores.',
    posterUrl: 'https://www.figma.com/api/mcp/asset/39561999-a31a-4786-8d17-859630e19d73',
    releaseDate: new Date('2018-12-05'),
    runtime: 128,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 4000,
    voteAverage: 58.0,
    budget: BigInt(100000000),
    revenue: BigInt(83672673),
    profit: BigInt(-16327327),
    genres: ['Ficção científica', 'Ação'],
  },
  {
    title: 'Vingadores: Ultimato',
    originalTitle: 'Avengers: Endgame',
    tagline: 'Parte da jornada é o fim.',
    overview: 'Após Thanos eliminar metade de todas as formas de vida, os Vingadores devem se reunir mais uma vez para desfazer as ações do Titã Louco e restaurar a ordem no universo.',
    releaseDate: new Date('2019-04-25'),
    runtime: 181,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 22000,
    voteAverage: 83.0,
    budget: BigInt(356000000),
    revenue: BigInt(2797800564),
    profit: BigInt(2441800564),
    genres: ['Ação', 'Aventura', 'Ficção Científica'],
  },
  {
    title: 'John Wick 3: Parabellum',
    originalTitle: 'John Wick: Chapter 3 - Parabellum',
    tagline: 'Se você quer paz, prepare-se para a guerra.',
    overview: 'O lendário assassino de aluguel John Wick está fugindo após matar um membro da guilda internacional de assassinos e com um preço de US$ 14 milhões por sua cabeça.',
    releaseDate: new Date('2019-05-16'),
    runtime: 131,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '16 ANOS',
    voteCount: 8500,
    voteAverage: 74.0,
    budget: BigInt(75000000),
    revenue: BigInt(326709727),
    profit: BigInt(251709727),
    genres: ['Ação', 'Crime', 'Thriller'],
  },
  {
    title: 'Toy Story 4',
    originalTitle: 'Toy Story 4',
    tagline: 'Um novo capítulo.',
    overview: 'Quando um novo brinquedo chamado Forky se junta a Woody e sua turma, uma viagem ao lado de velhos e novos amigos revela o quão grande o mundo pode ser para um brinquedo.',
    releaseDate: new Date('2019-06-20'),
    runtime: 100,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: 'Livre',
    voteCount: 11000,
    voteAverage: 75.0,
    budget: BigInt(200000000),
    revenue: BigInt(1073394593),
    profit: BigInt(873394593),
    genres: ['Animação', 'Aventura', 'Família', 'Comédia'],
  },
  {
    title: 'Coringa',
    originalTitle: 'Joker',
    tagline: 'Coloque um sorriso nesse rosto.',
    overview: 'Arthur Fleck, um comediante de stand-up fracassado, é levado à loucura e se torna o mestre do crime niilista conhecido como Coringa em Gotham City.',
    releaseDate: new Date('2019-10-03'),
    runtime: 122,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '16 ANOS',
    voteCount: 21000,
    voteAverage: 81.0,
    budget: BigInt(55000000),
    revenue: BigInt(1074458282),
    profit: BigInt(1019458282),
    genres: ['Crime', 'Thriller', 'Drama'],
  },
  {
    title: 'Parasita',
    originalTitle: 'Gisaengchung',
    tagline: 'Ato de bravura ou ato de loucura?',
    overview: 'Toda a família de Ki-taek está desempregada, vivendo num porão sujo. Quando o filho consegue um emprego como tutor na casa de uma família rica, as vidas das duas famílias começam a se entrelaçar de formas inesperadas.',
    releaseDate: new Date('2019-05-30'),
    runtime: 132,
    status: 'Lançado',
    originalLanguage: 'Coreano',
    certification: '16 ANOS',
    voteCount: 14000,
    voteAverage: 85.0,
    budget: BigInt(11400000),
    revenue: BigInt(258762056),
    profit: BigInt(247362056),
    genres: ['Comédia', 'Drama', 'Thriller'],
  },
  {
    title: 'O Rei Leão',
    originalTitle: 'The Lion King',
    tagline: 'O Rei retornou.',
    overview: 'Simba idolatra seu pai, o Rei Mufasa, e leva a sério seu próprio destino real. Mas nem todos no reino celebram a chegada do novo filhote.',
    releaseDate: new Date('2019-07-18'),
    runtime: 118,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: 'Livre',
    voteCount: 8000,
    voteAverage: 71.0,
    budget: BigInt(260000000),
    revenue: BigInt(1656943394),
    profit: BigInt(1396943394),
    genres: ['Aventura', 'Família'],
  },
  {
    title: 'Entre Facas e Segredos',
    originalTitle: 'Knives Out',
    tagline: 'Todo mundo tem um motivo. Ninguém tem a pista.',
    overview: 'Quando o renomado romancista criminal Harlan Thrombey é encontrado morto em sua propriedade logo após seu 85º aniversário, o inquisitivo e cortês detetive Benoit Blanc é misteriosamente recrutado para investigar.',
    releaseDate: new Date('2019-11-27'),
    runtime: 130,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '14 ANOS',
    voteCount: 9000,
    voteAverage: 78.0,
    budget: BigInt(40000000),
    revenue: BigInt(311400000),
    profit: BigInt(271400000),
    genres: ['Comédia', 'Mistério', 'Drama'],
  },
  {
    title: '1917',
    originalTitle: '1917',
    tagline: 'O tempo é o inimigo.',
    overview: 'No auge da Primeira Guerra Mundial, dois jovens soldados britânicos, Schofield e Blake, recebem uma missão aparentemente impossível: atravessar o território inimigo para entregar uma mensagem que pode salvar 1.600 de seus companheiros.',
    releaseDate: new Date('2019-12-25'),
    runtime: 119,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '14 ANOS',
    voteCount: 10000,
    voteAverage: 79.0,
    budget: BigInt(95000000),
    revenue: BigInt(384900000),
    profit: BigInt(289900000),
    genres: ['Guerra', 'Drama', 'Ação'],
  },
  {
    title: 'Ford vs Ferrari',
    originalTitle: 'Ford v Ferrari',
    tagline: 'Eles pegaram o sonho americano para dar uma volta.',
    overview: 'O visionário designer de carros americano Carroll Shelby e o destemido piloto britânico Ken Miles lutam contra a interferência corporativa, as leis da física e seus próprios demônios pessoais para construir um carro de corrida revolucionário para a Ford.',
    releaseDate: new Date('2019-11-15'),
    runtime: 152,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '12 ANOS',
    voteCount: 5000,
    voteAverage: 80.0,
    budget: BigInt(97000000),
    revenue: BigInt(225500000),
    profit: BigInt(128500000),
    genres: ['Drama', 'Ação', 'História'],
  },
  {
    title: 'Jojo Rabbit',
    originalTitle: 'Jojo Rabbit',
    tagline: 'Uma sátira contra o ódio.',
    overview: 'Um jovem garoto no exército de Hitler descobre que sua mãe está escondendo uma menina judia em sua casa.',
    releaseDate: new Date('2019-10-18'),
    runtime: 108,
    status: 'Lançado',
    originalLanguage: 'Inglês',
    certification: '14 ANOS',
    voteCount: 7000,
    voteAverage: 81.0,
    budget: BigInt(14000000),
    revenue: BigInt(90300000),
    profit: BigInt(76300000),
    genres: ['Comédia', 'Guerra', 'Drama'],
  },
];
