services:
  db:
    image: postgres:15-alpine
    container_name: cubos_movies_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-cubos_movies_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cubos_movies_app
    ports:
      - "5000:5000"
    environment:
      # Se você quiser usar o banco de dados do container 'db', a URL deve ser:
      # postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-cubos_movies_db}
      # Caso contrário, ele usará o DATABASE_URL definido no seu .env
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
